WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace WebApp
{
    public class HomeController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signinManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly ILogger<HomeController> logger;
        public HomeController(ILogger<HomeController> logger, RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signinManager)
        {
            this.logger = logger;
            this.signinManager = signinManager;
            this.userManager = userManager;
            this.roleManager = roleManager;
        }
        [HttpGet("/")]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Site here to view amazing photographies like the one here and sign up to upload different premium photographies and become a part of our great community.";

            return View();
        }

        public IActionResult Login(string returnUrl)
        {


            return View(new User()
            {
                ReturnUrl = returnUrl
            });
        } 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(User user){
            if (ModelState.IsValid)
            {
                var getUser = await userManager.FindByNameAsync(user.UserName);
                if (getUser != null)
                {
                    var result = await signinManager.PasswordSignInAsync(getUser, user.Password, false, false);
                    if (result.Succeeded)
                    {
                        if (string.IsNullOrEmpty(user.ReturnUrl))
                            return RedirectToAction("Index", "Home");
                        return RedirectToAction(user.ReturnUrl);
                    }
                }
            }
            ModelState.AddModelError("LoginError", "Username/Password not found");
            return View(user);
        }

        public IActionResult Register(){
            return View();
        }

        public async Task CreateRoles(){
            bool exist = await roleManager.RoleExistsAsync("ADMIN");
            if(!exist){
                var role = new IdentityRole
                {
                    Name = "ADMIN"
                };
                await roleManager.CreateAsync(role);
            }

            exist = await roleManager.RoleExistsAsync("USER");
            if (!exist)
            {
                var role = new IdentityRole
                {
                    Name = "USER"
                };
                await roleManager.CreateAsync(role);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(User user){
            if (ModelState.IsValid)
            {
                await CreateRoles();
                var registerUser = new ApplicationUser() { UserName = user.UserName, Email = user.Email };
                var result = await userManager.CreateAsync(registerUser, user.Password);
                await userManager.AddToRoleAsync(registerUser, "USER");
                if (result.Succeeded)
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            else
            {
                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();
                logger.LogError(errors.ToString());
            }
            return View(user);

        }
        [Authorize]
        public async Task<IActionResult> Logout(){
            await signinManager.SignOutAsync();
            return RedirectToAction("Index", "Home");

        }



        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.AspNetCore.Mvc;

namespace WebApp
{
    public class PageController : Controller
    {
        public PageController()
        {
        }

        

        public IActionResult ViewPage(string category){
            string c = category;
            Image i = new Image();
            List<Image> images = i.SelectByType(category);
            ImageViewModel imageModel = new ImageViewModel
            {
                Images = images,
                Image = i
            };

            return View(imageModel);
        }
        public ActionResult Download(string imagePath){
            var absolutePath = "/Users/Merry/Projects/WebApp/WebApp/wwwroot/uploads/"+imagePath;
            return PhysicalFile(absolutePath, "image/*", imagePath);


        }

    }
}

WebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}


<!-- Jumbotron -->
<div class="jumbotron p-0 m-0">

    <!-- Card image -->
    <div class="view overlay rounded-top">
        <img src="~/images/about.jpg" class="img-fluid" alt="Sample image">
        <a href="#">
            <div class="mask rgba-white-slight"></div>
        </a>
    </div>

    <!-- Card content -->
    <div class="card-body text-center carousel-caption" style="top:20%;">

        <!-- Title -->

        <h1 class="card-title h1 my-2"><strong>Photograph Shelf</strong></h1>
        <!-- Text -->
        <p class="card-text py-2" style="margin-bottom:4%;">@ViewData["Message"]</p>

    </div>

</div>
<!-- Jumbotron -->

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="thumbnail">
                <div class="py-2">
                    <h4>Arts</h4>
                </div>
                <a asp-controller="Page" asp-action="ViewPage" asp-route-category="Arts">
                    <img src="~/images/art.jpeg" class="rounded-circle" alt="Arts">
                </a>
                <figcaption class="figure-caption">View photographs of different arts and paintings</figcaption>
                <br>
            </div>
        </div>

        <div class="col-sm-3 col-md-3">
            <div class="thumbnail">
                <div class="py-2">
                    <h4>Landscapes</h4>
                </div>
                <a asp-controller="Page" asp-action="ViewPage" asp-route-category="Landscapes">
                    <img src="~/images/landscape.jpg" class="rounded-circle" alt="Landscapes">
                </a>
                <figcaption class="figure-caption">View photographs of picturesque landscapes</figcaption>
                <br>
            </div>
        </div>
        <div class="col-sm-3 col-md-3" style="margin-right:0">
            <div class="thumbnail">
                <div class="py-2">
                    <h4>People</h4>
                </div>
                <a asp-controller="Page" asp-action="ViewPage" asp-route-category="People">
                    <img src="~/images/people.jpg" class="rounded-circle" alt="People">
                </a>
                <figcaption class="figure-caption">View photographs of different people</figcaption>
                <br>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="thumbnail">
                <div class="py-2">
                    <h4>Places</h4>
                </div>
                <a asp-controller="Page" asp-action="ViewPage" asp-route-category="Places">
                    <img src="~/images/default.jpg" class="rounded-circle" alt="Places">
                </a>
                <figcaption class="figure-caption">View photographs of different places and cities</figcaption>
                <br>
            </div>
        </div>
        <div class="col-sm-3 col-md-3">
            <div class="thumbnail">
                <div class="py-2">
                    <h4>Foods</h4>
                </div>
                <a asp-controller="Page" asp-action="ViewPage" asp-route-category="Foods">
                    <img src="~/images/food.jpeg" class="rounded-circle" alt="Food">
                </a>
                <figcaption class="figure-caption">Delve into photographs of amazing food</figcaption>
                <br>
            </div>
        </div>
        <div class="col-sm-3 col-md-3" style="margin-right:0">
            <div class="thumbnail">
                <div class="py-2">
                    <h4>Others</h4>
                </div>
                <a asp-controller="Page" asp-action="ViewPage" asp-route-category="Others">
                    <img src="~/images/others.jpg" class="rounded-circle" alt="Others">
                </a>
                <figcaption class="figure-caption">View photographs of mixed categories</figcaption>
                <br>
            </div>
        </div>
    </div>
    <br />

</div>

WebApp/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login";
}
@model User 

<div class="jumbotron p-0 m-0">

    <!-- Card image -->
    <div class="view overlay rounded-top">
        <img src="~/images/login_image.jpeg" class="img-fluid" alt="Sample image" style="height:550px;">
        <a href="#">
            <div class="mask rgba-white-slight"></div>
        </a>
    </div>

    <!-- Card content -->
    <div class="card-body carousel-caption" style="top:20%;">

        <!-- Title -->

            <div class="row justify-content-center">
                <div class="col-md-offset-5 col-md-4">
                    <form asp-controller="Home" asp-action="Login" method="post">

                        <div class="form-login">

                            <br>
                            <h4>Login Form</h4>
                            <br>
                            <div asp-validation-summary="ModelOnly"></div>
                            <input type="text" asp-for="UserName" class="form-control input-sm chat-input" placeholder="Username" />
                            <span asp-validation-for="UserName" class="error"></span>
                            <br><br>
                            <input type="password" asp-for="Password" class="form-control input-sm chat-input" placeholder="Password" />
                            <span asp-validation-for="Password" class="error"></span>
                            <br><br>
                            <input type="hidden" asp-for="Email" class="form-control input-sm chat-input" value="abc@gmail.com" />
                            <div class="wrapper">
                                <span class="group-btn">
                                    <button class="btn btn-primary btn-md round"> LOGIN <i class="fa fa-sign-in"></i></button>

                                </span>
                            </div>
                            <br />
                            @if (!ViewData.ModelState.IsValid)
                            {
                             <div class="alert alert-danger">@Html.ValidationMessage("LoginError")</div>
                            }
                        </div>
                      </form>
                </div>
        </div>
     </div>
</div>
<!-- Jumbotron -->

WebApp/Views/Home/Register.cshtml

@{
    ViewData["Title"] = "Register";
}
@model User
<div class="jumbotron p-0 m-0">
    <!-- Card image -->
    <div class="view overlay rounded-top">
        <img src="~/images/login_image.jpeg" class="img-fluid" alt="Sample image" style="height:510px;">
        <a href="#">
            <div class="mask rgba-white-slight"></div>
        </a>
    </div>
    <!-- Card content -->
    <div class="card-body carousel-caption" style="top:15%;">
        <!-- Title -->
        <div class="row justify-content-center">
            <div class="col-md-offset-5 col-md-4">
                <form asp-controller="Home" asp-action="Register" method="post">
                    <div class="form-login">
                        <br>
                        <h4>Registration Form</h4>
                        <input type="hidden" asp-for="ReturnUrl"/>
                        <br>
                        <input type="email" asp-for="Email" class="form-control input-sm chat-input" placeholder="Email" />
                        <span asp-validation-for="Email" class="error"></span>
                        <br><br>
                        <input type="text" asp-for="UserName" class="form-control input-sm chat-input" placeholder="Username" />
                        <span asp-validation-for="UserName" class="error"></span>
                        <br><br>
                        <input type="password" asp-for="Password" class="form-control input-sm chat-input" placeholder="Password" />
                        <span asp-validation-for="Password" class="error"></span>
                        <br><br>
                        <div class="wrapper">
                            <span class="group-btn">
                                <button class="btn btn-success btn-md round"> Register <i class="fa fa-sign-in"></i></button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Jumbotron -->